### ISSUE TITLE
قابلیت تغییر پورت اتصال به سرور

### ISSUE THREAD

**Issue by randomguy-on-internet** [aleskxyz/reality-ezpz#1]
سلام امکان تعیین پورت اتصالی به کانفیگ رو در اختیار کاربر بزارید، بعضی از سرور ها پورت هاشون محدوده.

**Comment by aleskxyz** [comment]
> سلام امکان تعیین پورت اتصالی به کانفیگ رو در اختیار کاربر بزارید، بعضی از سرور ها پورت هاشون محدوده.

سلام
تمام تلاش این پروتکل بر اینه که شبیه یک وبسایت عادی به نظر برسه. با تغییر پورت به چیزی به جز ۸۰ و ۴۴۳ سرور شما کاملا در معرض شناسایی قرار میگیره.
