### ISSUE TITLE
Add XUDP and xtls-rprx-vision-udp443

### ISSUE THREAD

**Issue by misagh72** [aleskxyz/reality-ezpz#10]
ممنون از کدتون میشه هم xtls-rprx-vision-udp443 و Xudp رو اضاف کنید به کدتون mux هم برای xdp هست

"mux": { # for XUDP
                "enabled": false, # if want use XUDP enable this
                "concurrency": -1,
                "xudpConcurrency": 1,
                "xudpProxyUDP443": "allow"
                # only Xray, Vision, port 443
                # If you want more details go to these pages
                # https://github.com/XTLS/Xray-core/issues/1963
                # https://xtls.github.io/config/outbound.html#muxobject
                # https://github.com/XTLS/Xray-core/discussions/252

**Comment by aleskxyz** [comment]
> ممنون از کدتون میشه هم xtls-rprx-vision-udp443 و Xudp رو اضاف کنید به کدتون mux هم برای xdp هست
> 
> "mux": { # for XUDP "enabled": false, # if want use XUDP enable this "concurrency": -1, "xudpConcurrency": 1, "xudpProxyUDP443": "allow" # only Xray, Vision, port 443 # If you want more details go to these pages # [XTLS/Xray-core#1963](https://github.com/XTLS/Xray-core/issues/1963) # https://xtls.github.io/config/outbound.html#muxobject # [XTLS/Xray-core#252](https://github.com/XTLS/Xray-core/discussions/252)

این تنظیمات مربوط به سمت کلایت هست و نه سرور
در مورد mux به خاطر اینکه تنظیمات رو برای کلاینت موبایل درست میکنه، چنین آپشنی توی گوشی نیست.
تنظیمات flow رو هم واسه کلاینت به xtls-rprx-vision-udp443 تغییر دادم
https://github.com/aleskxyz/reality-ezpz/commit/f7c057b523a9b8a9b779e12c5cf533fd55eac433
طبق تستی که کردم به نظر میرسه مشکل سازگاری نداره و کار میکنه
