### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by aleksan149** [aleskxyz/reality-ezpz#101]
Друзья, реализуйте пожалуйста функцию бэкапа с данными пользователей. Чтобы можно было в случае блока переехать на другой сервер и не менять настройки на стороне клиента.

**Comment by aleskxyz** [comment]
Use this command to copy all the files and configuration from current server to new server:
```
scp -r /opt/reality-ezpz/ <username>@<new-ip-address>:/opt/reality-ezpz/
```
Replace `<username>` and `<new-ip-address>` with correct values.
Then run the script again in the new server.
Recheck that the "Configuration" > "Server Address" is showing your new server ip or your domain name.
