### ISSUE TITLE
Bridge

### ISSUE THREAD

**Issue by aleksan149** [aleskxyz/reality-ezpz#102]
Друг, твой проект великолепен! Благодарю тебя за это!
Скажи мне, как можно реализовать мост из двух VPS? 
По сценарию клиент подключается к 1vps в своей стране и ходит на местные сайты через него. А для заблокированных сайтов  1vps маршрутизирует трафик на 2vps в другой стране. 
Заранее благодарю!
![photo_2023-10-12 21 13 05 (1)](https://github.com/aleskxyz/reality-ezpz/assets/89018329/640afe7d-5641-4160-a899-919cfcba71f9)

**Comment by aleskxyz** [comment]
You can create a setup like this but it is not an easy one click setup.
If I find time I'll work on that

**Comment by aleksan149** [comment]
Благодарю тебя! Буду ждать!
