### ISSUE TITLE
CRYPTO_ERROR letsencrypt

### ISSUE THREAD

**Issue by dev-ehsan-babaei** [aleskxyz/reality-ezpz#104]
I've got certificate via your letsencrypt security mode and changed transport to hysteria 2.
However Nekobox says:
tls: failed to verify certrificate: x509: certificate relies on legacy Common Name field, use SANs instead.
I can connect by enabling "Allow insecure" btw.
I could use letsencrypt mode before. Is there any new changes that made this error?

**Comment by aleskxyz** [comment]
maybe new certificates are not loaded correctly.
You can try to restart the service with this command:
```
bash <(curl -sL https://bit.ly/realityez) -r
```
Our delete everything with this command:
```
bash <(curl -sL https://bit.ly/realityez) -u
```
And run the script again
