### ISSUE TITLE
Certificates in NekoBox

### ISSUE THREAD

**Issue by Ilaprgg2** [aleskxyz/reality-ezpz#105]
سلام
در برنامه NekoBox قسمتی هست به نام Certificates
هم برای tuic و هم برای Hysteria2 این قسمت خالیه

این برای سرتیفیکیت tls هست؟
اگه قرار داشته باشه بهتر نیست؟

ممنون از اسکریپت خوب شما

**Comment by aleskxyz** [comment]
سلام
اون فیلد کاربردی توی پیاده سازی فعلی ما نداره
ممنون
