### ISSUE TITLE
ERROR: Unsupported distribution 'amzn'

### ISSUE THREAD

**Issue by AhvazBangeleh** [aleskxyz/reality-ezpz#111]
سلام و سپاس
I am getting "ERROR: Unsupported distribution 'amzn'" trying to execute either of the commands. 
bash <(curl -sL https://bit.ly/realityez)
bash <(curl -sL https://raw.githubusercontent.com/aleskxyz/reality-ezpz/master/reality-ezpz.sh)
The server is Amazon LightSail running the latest Amazon Linux 2023.

Thank you!
ممنون

**Comment by aleskxyz** [comment]
سلام
داکر رو باید خودت نصب کنی تا به این ارور نخوری
البته نمیدونم در ادامه ارور بده یا نه

**Comment by AhvazBangeleh** [comment]
ممنونم
