### ISSUE TITLE
مواجه شدن با ارور کانفیگ ها فقط روی اینترنت همراه اول

### ISSUE THREAD

**Issue by mimabbasi** [aleskxyz/reality-ezpz#115]
سلام دوست عزیز
اول از همه چیز سپاسگزای و خسته نباشید میگم بابت زحمات زیادی ک برای ساخت این اسکریپت فوق العاده میکشید.
در چند روز اخیر هر سرور از هر دیتا سنتر و یا لوکیشن متفاوت میگیرم و اسکریپت رو نصب میکنم بعد چند ساعت یا نهایتا 1 روز، کانفیگ ها برای اینترنت همراه اول از کار میفوفتن و با این پیغام مواجه میشم net http tls handshake timeout
و جالب اینکه برای سایر اینترنت ها مثل ایرانسل و یا وای فای این مشکل وجود نداره و اتصال همچنان برقراره
شما چه راه حلی برای رفع این مشکل پیشنهاد میدید؟

**Comment by aleskxyz** [comment]
سلام
متاسفانه در مورد اشکالاتی که اپراتورها ایجاد میکنن ایده ای ندارم.
