### ISSUE TITLE
Choosing between tcp and udp format in hysteria and tuic configurations 

### ISSUE THREAD

**Issue by itsmostafa75** [aleskxyz/reality-ezpz#117]
اگر براتون مقدور هست لطفا من رو در این مورد زیر،راهنمایی بفرمایید.

هیستریا ۲،هم udp هم tcp رو ساپورت میکنه.
بر روی اکثر شرکتهای adsl، پروتکل udp مسدود هستش.
من برای ساخت کانفیگ هیستریا۲ و توییک،از اسکریپت شما استفاده میکنم که بصورت پیشفرض،کانفگیهای ساخته شده،از udp استفاده میکنند و به همین خاطر کانفیگهای ساخته شده بر روی adsl، فعال نیستن.

چگونه میتونم در اسکریپت شما،فایل تنظیمات مربوطه رو پیدا کنم و به جای استفاده از udp،حالت tcp را انتخاب کنم؟

**Comment by aleskxyz** [comment]
مساله اینجاست که هیستریا و توییک مثلا دارن ترافیک quic رو که روی udp هست شبیه سازی میکنن. اگه بره روی  tcp میشه یه چیز دیگه که شناسایی سرور رو برای بستن ای پی ساده میکنه

**Comment by itsmostafa75** [comment]
آهان
این مورد رو نمیدونستم
البته من برای سرور شخصی میخوام و چون تک نفر استفاده میکنم شاید خیلی در معرض فیلتر نباشم اما حرف شما متین هست.
ممنونم،مرسی از پاسختون🌹

**Comment by AkramiPro** [comment]
فقط برای روشن شدن مسئله خواستم توضیح بدم
هیستریا فقط با udp کار میکنه . چون اساس کارش روی quic هست 
اینکه tcp ساپورت میکنه یعنی میتونه ترافیک tcp رو هم از تانل خودش عبور بده 
شما حتی میتونی براش تنظیم کنی که ترافیک udp رو از خودش عبور نده و فقط ترافیک tcp کار کنه . ولی همچنان تانلی که باز میکنه روی udp هست


![image](https://github.com/aleskxyz/reality-ezpz/assets/54323929/dcba602d-f046-4879-942c-d4e400bc40a0)

**Comment by itsmostafa75** [comment]
مرسی از توضیح دقیق شما.من الان فقط این مورد برام هنوز سوال هست که پس چطوری یک سری کانفیگ هیستریا و توئیک که تو کانال های تلگرامی بصورت رایگان قرار میدن،بر روی اپراتورهایی مثل مخابرات که udp بسته هستش هم کار می‌کنه.میشه من همین‌جا یه کانفیگشون رو بفرستم یا یکی از کانال هایی که اینجور کانفیگ هارو میزاره براتون اینجا ایدیش رو بزارم تا شما خودتون بررسی کنین؟

**Comment by mohamadm0meni** [comment]
> مرسی از توضیح دقیق شما.من الان فقط این مورد برام هنوز سوال هست که پس چطوری یک سری کانفیگ هیستریا و توئیک که تو کانال های تلگرامی بصورت رایگان قرار میدن،بر روی اپراتورهایی مثل مخابرات که udp بسته هستش هم کار می‌کنه.میشه من همین‌جا یه کانفیگشون رو بفرستم یا یکی از کانال هایی که اینجور کانفیگ هارو میزاره براتون اینجا ایدیش رو بزارم تا شما خودتون بررسی کنین؟

لطفا اگر دارید بفرستید

**Comment by itsmostafa75** [comment]
این لینک پست تلگرامی امشبشون هست
تقریبا ۸۰ درصد کانفیگ های هیستریا وتوئیکشون روی مخابرات هم کار میکنه.
https://t.me/EUT_VPN/259

اگر پستشون رو پاک کرده بودن،قطعا پست جدید تری گذاشتن که کانفیگ هاش فعاله
به همین خاطر آیدی کانالشون رو هم میزازم
https://t.me/EUT_VPN


واقعا اگر این مورد رو بررسی کنین ممنون میشم
خیلیی کاربردیه
خیلی واقعا بهش نیاز دارم
ممنونم از پیگیری شما🌹🌹

**Comment by aleskxyz** [comment]
@itsmostafa75 
به نظر میاد اونها دارن از پورتهای مختلف و بالای 20 هزار استفاده میکنن
شما هم میتونید امتحان کنید ببینید کار میکنه یا نه

**Comment by itsmostafa75** [comment]
> @itsmostafa75 
> به نظر میاد اونها دارن از پورتهای مختلف و بالای 20 هزار استفاده میکنن
> شما هم میتونید امتحان کنید ببینید کار میکنه یا نه

من هم همینکارو کردم ولی پاسخ نداد متاسفانه
