### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by mfat** [aleskxyz/reality-ezpz#12]
Hi I'm getting this error in v2rayNG after trying the default configuration and also custom configurations.

bash <(curl -sL https://bit.ly/realityez) -d yahoo.com -t grpc --port 16514

**Comment by aleskxyz** [comment]
> Update: the generated config works with Nekoray (with singbox core) and WingX on iPhone. Tested other clients like shadowrocket, v2rayNG and Nekobox. None of them worked.

Can you test again with the new version of script?

**Comment by esahekmat** [comment]
Same Issue with the current master, I tried the script with the pull request #14 and it works without issue
