### ISSUE TITLE
نحوه آپدیت اسکریپت

### ISSUE THREAD

**Issue by itsmostafa75** [aleskxyz/reality-ezpz#120]
درود
علی اقا گفته شد شما کد رو اپدیت کردین و الان خروجی رو به هر دو فرم ipv4 و ipv6 میشه گرفت.من برای اپدیت اسکریپت،دوباره همون کد نصبش رو اجرا کردم و موقع خروجی گرفتن،فقط یک مدل ipv4،نمایش داد.
من اشتباه اپدیت کردم اسکریپت رو که خروجی ipv6 نداشت ؟

یا اصلا باید بصورت دستی خروجی ipv6 رو فعال کنم و خودش اتومات برای همه کانفیگ ها،دو فرمت ipv4 و ipv6 رونمیده؟
ممنون میشم راهنمایی بفرمایید 🌹

**Comment by aleskxyz** [comment]
سلام
احتمالا سرور شما کلا ipv6 نداره
لازمه سرور ipv6 داشته باشه
این دستور رو اجرا کن، اگه خروجی نداشت یعنی سرور شما ipv6 نداره
```
curl -fsSL --ipv6 https://cloudflare.com/cdn-cgi/trace 2> /dev/null | grep ip
```
