### ISSUE TITLE
تغییر مقادیر sni و dest

### ISSUE THREAD

**Issue by mhmb87** [aleskxyz/reality-ezpz#121]
سلام
در پنل شما فقط امکان تغییر sni هست و dest رو نمیشه جداگانه تغییر داد لطفا راهنمایی کنید
ممنون

**Comment by aleskxyz** [comment]
سلام
چنین چیزی توی تنظیمات سمت سرور ممکن نیست و کلا یه تنظیم اشتباه محسوب میشه
