### ISSUE TITLE
مشکل برنامه سینگ باکس با لینک کانفیگ

### ISSUE THREAD

**Issue by Mhmmd-h17m** [aleskxyz/reality-ezpz#130]
سلام من میخوام کانفیگ های هیستریا و روی ios استفاده کنم واسه همین اول کانفیگ و توی نکوباکس توی اندروید وارد میکنم بعد یه خروجی json ازش میگیرم و روی اپ sing-box که وارد میکنم ارور unknown field hop-interval میده.
میشه لطفا راهنماییم کنید.

**Comment by aleskxyz** [comment]
سلام
این ربطی به این اسکریپت نداره ولی طبق ارور مشخصه که اپ ios فیلد hop-interval رو از فایلی که دارید وارد میکنید متوجه نمیشه.
اون خط رو پاک کنید شاید کار کرد
