### ISSUE TITLE
مشکل نصب روی سرور ایران

### ISSUE THREAD

**Issue by mohamadm0meni** [aleskxyz/reality-ezpz#134]
![2](https://github.com/aleskxyz/reality-ezpz/assets/77540335/435ba82d-60f5-48c0-8c16-af64a619539b)

روی سرور ایران میخوام نصب کنم این ارور رو میده
راه حل چیست استاد

**Comment by aleskxyz** [comment]
داکر ایران رو تحریم کرده
از شکن استفاده کنید

**Comment by mohamadm0meni** [comment]
درست شد ممنون استاد @aleskxyz
