### ISSUE TITLE
از کار افتادن ربات تلگرام

### ISSUE THREAD

**Issue by Zeroniixx** [aleskxyz/reality-ezpz#137]
با درود
ربات تلگرام از کار افتاده
فکر‌کنم بعد از apt update && upgrade این مشکل پیش اومد
هیچ مدله دیگه کار نمیکنه
توکن جدید گرفتم
بات جدید ساختم
کل پنل رو از نو نصب کردم…
Os های متفاوت امتحان کردم
![IMG_2865](https://github.com/aleskxyz/reality-ezpz/assets/154655792/e19cb397-9e81-4c84-8598-c9f09c47a460)

**Comment by alirezaalipour59** [comment]
منم این مشکل رو پیدا کردم

**Comment by aleskxyz** [comment]
سلام
مشکل برطزف شد
یه بار دستور نصب رو اجرا کنید تا اپدیت بشه
