### ISSUE TITLE
مشکل صدا یا ویدیو 

### ISSUE THREAD

**Issue by EsiNakamoto** [aleskxyz/reality-ezpz#139]
سلام من وقتی با v2rayNG وصل میشم به سرور بعضی سرویس های صوتی مثل castbox کار نمیکنه. مشکل از چیه ؟ پروتکل نباید tcp باشه؟

**Comment by aleskxyz** [comment]
میتونید بقیه پروتکلها به جز tcp رو تست کنید احتمالا حل بشه

**Comment by EsiNakamoto** [comment]
باشه تست میکنم. راستی الان که ریلیتی رو میزنن بنظر شما کدوم راه بهتر جواب میده؟

**Comment by aleskxyz** [comment]
دامنه بگیر بزار پشت کلادفلیر یا اروان با پروتکل ws
