### ISSUE TITLE
کار نکردن اسکریپت

### ISSUE THREAD

**Issue by mimabbasi** [aleskxyz/reality-ezpz#140]
سلام دوست عزیز 
چرا جدیدا اسکریپت روی هیچ اپراتوری کار نمیکنه؟
روی چندین سرور تست کردم اما جواب نگرفتم
و جالب ایجاست سرورهایی که قبلا اسکریپت روش نصب بود فعاله و کار میکنه
جدیدا باید تنظیمات خاص یا اضافه ای انجام داد؟؟

**Comment by aleskxyz** [comment]
این مساله ربطی به اسکریپت نداره
احتمالا سرورهای قدیمی شما به خاطر کانفیگ ثابتی که داشتن عملا وایت لیست شدن ولی سرورهای جدید عمیقتر بررسی میشن و بلاک میشن
