### ISSUE TITLE
مشکل در نصب

### ISSUE THREAD

**Issue by mrmasiha0** [aleskxyz/reality-ezpz#142]
سلام من میخوام اسکریپت رو نصب کنم و با پیام زیر مواجه میشم و نصب نمیشه. قبلا بارها اسکریپت رو نصب کرده ام ولی الان هرکاری می کنم نمیشه:

# Executing docker install script, commit: e5543d473431b782227f8908005543bb4389b                                                                    8de
+ sh -c 'apt-get update -qq >/dev/null'

**Comment by mrmasiha0** [comment]
الان سرور رو ریبیلد کردم باز رفتم برای نصب این خطا رو میده:

dev/fd/63: line 2395: /usr/bin/jq: cannot execute binary file: Exec format error

**Comment by aleskxyz** [comment]
سیستم عاملتون چیه؟

**Comment by mrmasiha0** [comment]
ubuntu 22

**Comment by aleskxyz** [comment]
> سلام من میخوام اسکریپت رو نصب کنم و با پیام زیر مواجه میشم و نصب نمیشه. قبلا بارها اسکریپت رو نصب کرده ام ولی الان هرکاری می کنم نمیشه:
> 
> 
> 
> # Executing docker install script, commit: e5543d473431b782227f8908005543bb4389b                                                                    8de
> + sh -c 'apt-get update -qq >/dev/null'
> 
> 

این که پیام عادی نصبش هست
باید صبر کنید تا نصبش تموم شه
شاید بسته به سرعت شبکه یا کیفیت سرور طولانی بشه
من الان روی یه سرور اوبونتو ۲۲ توی هتزنر تست کردم و بدون مشکل نصب شد

**Comment by mrmasiha0** [comment]
من بیشتر از یک ساعت صبر کردم و 3 بار هم امتحان کردم. همینجا گیر می کنه.

**Comment by aleskxyz** [comment]
> من بیشتر از یک ساعت صبر کردم و 3 بار هم امتحان کردم. همینجا گیر می کنه.

سرورتون رو از کجا گرفتید؟
دقیقا لینک خریدش رو بدید

**Comment by mrmasiha0** [comment]
yottasrc.com

**Comment by aleskxyz** [comment]
من یه سرور از اینجا خریدم و اسکریپت رو تست کردم و بدون مشکل کار کرد.

**Comment by mrmasiha0** [comment]
اگر امکانش هست من یوزر پسورد سرور رو میدم شما چک کنید.من هر کاری می کنم جواب نمیده.
