### ISSUE TITLE
ربات تلگرام 

### ISSUE THREAD

**Issue by mahmoodhabibi333** [aleskxyz/reality-ezpz#146]
تمام مراحل را درست رفتم ولی ربات کار نکرد

**Comment by aleskxyz** [comment]
متاسفانه کمکی از دستم برنمیاد چون ربات داره کار میکنه و شما هیچ اطلاعات اضافه ای ندادید

**Comment by mahmoodhabibi333** [comment]
میخواستم اگه اکان داره مثال بزنید بگید دقیقا توکن و آی دی رو چجوری داخل اسکریپت باید قرار بدهم
bash <(curl -sL https://bit.ly/realityez) --enable-tgbot true --tgbot-token <telegram-bot-6475723240:AAGNKRw_oFyIVltdIH6T0_asDZyNI79IiRE> --tgbot-admins=<your-telegram-stuicabot>
این درسته؟؟

**Comment by aleskxyz** [comment]
> میخواستم اگه امکان داره مثال بزنید بگید دقیقا توکن و آی دی رو چجوری داخل اسکریپت باید قرار بدهم bash <(curl -sL https://bit.ly/realityez) --enable-tgbot true --tgbot-token telegram-bot-6475723240:AAGNKRw_oFyIVltdIH6T0_asDZyNI79IiRE --tgbot-admins= این درسته؟؟

ببخشید دیر جواب میدم ولی اگه میخواید از طریق کامندلاین فعالش کنید طبق راهنما باید به این شکل اقدام کنید:

```
bash <(curl -sL https://bit.ly/realityez) --enable-tgbot true --tgbot-token 00000000:aaaaaaa_bbbbbb_cccccc --tgbot-admins telegram_username
```
