### ISSUE TITLE
مشکل در نصب warp

### ISSUE THREAD

**Issue by mrmasiha0** [aleskxyz/reality-ezpz#148]
سلام ممنون از زحمات شما 
من هنگام فعال کردن وارپ در پنل با خطای زیر مواجه میشم:

 WARP account creation error  
                                                          
2024/02/13 08:00:08 Using config file:                   
/data/wgcf-account.toml^M                                
 2024/02/13 08:00:13 Post                                 
 "https://api.cloudflareclient.com/v0a1922/reg": read tcp 
 172.17.0.2:39272->104.19.237.24:443: read: connection    
 reset by peer^M                                          
 WARP account creation has been failed!

**Comment by aleskxyz** [comment]
سلام
به نظر میاد کلادفلیر به ای پی سرور شما سرویس نمیده و کانکشن رو قطع میکنه. احتمالا از سمت رنج ای پی یا دیتاسنتری سرور شما اونجاست ترافیک الوده و مشکوک به سمت کلادفلیر زیاد ارسال شده که ای پی رو بسته

**Comment by mrmasiha0** [comment]
ممنونم از راهنمایی
