### ISSUE TITLE
calculate traffic

### ISSUE THREAD

**Issue by smaghili** [aleskxyz/reality-ezpz#15]
hi . You have a very good panel
Please add the ability to calculate traffic for each user to the panel.

**Comment by SalarAbapour** [comment]
> hi . You have a very good panel Please add the ability to calculate traffic for each user to the panel.

**Comment by aleskxyz** [comment]
> hi . You have a very good panel Please add the ability to calculate traffic for each user to the panel.

This is not a panel, this script is a simple configurator. It install and configs the services in your server. Traffic calculation is out of scope of a simple configurator. it is an independent service.
The main goal of this script is making configuration easy for everyone.
Billing and accounting feature is for commercial purposes that definitely goes beyond the goals of this script!
