### ISSUE TITLE
گرفتن بکاپ و انتقال به سرور دیگه

### ISSUE THREAD

**Issue by mehdi7arfand10** [aleskxyz/reality-ezpz#152]
سلام وقت بخیر
میشه راهنماییم کنین که چطور میتونم از کاربرام بکاپ بگیرم و روی یک سرور دیگه قرار بدم؟
هم با دستور هم تو پنل create backup رو میزنم ولی این ارور رو میده
curl: (6) Could not resolve host: free.keep.sh
Error in uploading backup file

ممنون میشم پیامم رو ببینین و جواب بدین 🙏

**Comment by aleskxyz** [comment]
> سلام وقت بخیر میشه راهنماییم کنین که چطور میتونم از کاربرام بکاپ بگیرم و روی یک سرور دیگه قرار بدم؟ هم با دستور هم تو پنل create backup رو میزنم ولی این ارور رو میده curl: (6) Could not resolve host: free.keep.sh Error in uploading backup file
> 
> ممنون میشم پیامم رو ببینین و جواب بدین 🙏

سلام
مشکل توی نسخه جدید برطرف شد
