### ISSUE TITLE
از کار افتادن کانفیگ های tuic 

### ISSUE THREAD

**Issue by mohamadm0meni** [aleskxyz/reality-ezpz#156]
سلام حدود 4 ماه هست دارم از tuic استفاده میکنم 
![image](https://github.com/aleskxyz/reality-ezpz/assets/77540335/8042924a-30f1-48b1-80a9-0c6f74992466)
 این ارور از دیشب داره میده راه حل چیست ؟
اس اس ال تموم شده ؟

**Comment by mohamadm0meni** [comment]
چطوری ssl رو تمدید کنیم لطفا بگید ...

**Comment by aleskxyz** [comment]
سلام
اصولا خودش به صورت خودکار باید تمدیدش کنه ولی با اجرای دستور زیر یه بار سرویس‌ها رو ریستارت کنید شاید درست شد
```
bash <(curl -sL https://bit.ly/realityez) -r
```

**Comment by mohamadm0meni** [comment]
![image](https://github.com/aleskxyz/reality-ezpz/assets/77540335/eb86b137-cb59-4341-a95c-c3ead475eb0b)
انجام دادم ولی بازم درست نشد اگر نمیشه لطفا مشکل بک آپ رو میشه حل کنید بتونم کاربرامو ببرم روی یک سرور جدید

**Comment by aleskxyz** [comment]
> ![image](https://github.com/aleskxyz/reality-ezpz/assets/77540335/eb86b137-cb59-4341-a95c-c3ead475eb0b)
> انجام دادم ولی بازم درست نشد اگر نمیشه لطفا مشکل بک آپ رو میشه حل کنید بتونم کاربرامو ببرم روی یک سرور جدید

اول مطمین شید از اینکه ساب دامینی که روی سرور ست کردید داره کار میکنه
واسه این کار سابدامین رو توی مرورگر بزنید اگه صفحه nginx باز شد یعنی درسته.
اگه سابدامین اوکی بود، بعد دستورات زیر رو اجرا کنید تا کل گواهینامه ها پاک بشه و از اول ساخته بشه.
```
cd /opt/reality-ezpz
docker compose down
rm -rf certificate
rm -rf certbot
bash <(curl -sL https://bit.ly/realityez)
```
توی مورد شما بکاپ مشکل رو حل نمیکنه چون وقتی بک اپ رو برگردونید باز هم همون گواهی قبلی برمیگرده
مشکل بک اپ رو به‌زودی حل میکنم
