### ISSUE TITLE
ارور دادن هنگام گرفتن بک اپ

### ISSUE THREAD

**Issue by mohamadm0meni** [aleskxyz/reality-ezpz#157]
![image](https://github.com/aleskxyz/reality-ezpz/assets/77540335/fc0dc163-9600-414c-9568-434b1321b8da)

**Comment by aleskxyz** [comment]
Dup https://github.com/aleskxyz/reality-ezpz/issues/152

**Comment by aleskxyz** [comment]
مشکل برطرف شد

**Comment by mohamadm0meni** [comment]
دمتون گرم تشکر فراوان
