### ISSUE TITLE
relay tunnel

### ISSUE THREAD

**Issue by mahdifar** [aleskxyz/reality-ezpz#16]
سلام خسته نباشی
کد بسیار خوب و جالبیه فقط یه ایده‌ای داشتم اونم این بود که بخشی به عنوان add tunnel یا با عنوان دیگه‌ای پیاده بشه که تو فایل کانفیگ به بخش outbound اضافه بشه و یک تانل بسازه .

**Comment by aleskxyz** [comment]
> سلام خسته نباشی کد بسیار خوب و جالبیه فقط یه ایده‌ای داشتم اونم این بود که بخشی به عنوان add tunnel یا با عنوان دیگه‌ای پیاده بشه که تو فایل کانفیگ به بخش outbound اضافه بشه و یک تانل بسازه .

سلام
سناریویی که دارید چی هست دقیقا؟

**Comment by mahdifar** [comment]
به این شکل که ما کد bash که شما نوشتی رو توی vps ایران اجرا کنیم و بهش یه کد کانکشن یا یه کانفیگ json که اطلاعات اتصال به سرور نهایی که خارج از ایرانه رو بدیم و برامون یه تانل بسازه.

من کد رو توی vps ایران اجرا کردم ، مشکلی که هست اینه که داکر ایران رو تحریم کرده و نمیشه با ip ایران ازش استفاده کرد ، من تونستم با dns دورش بزنم.
 ولی خب با چن بار تلاش تونستم نصبش کنم. ( کوتاه کننده لینک bitly هم کار نمیکرد. )

به نظرم این شکلی واسه خیلی از کاربرا سودمنده ، چون شما یه tui ساختی و میشه به راحتی باهاش یوزر ساخت و خیلیا نتونستن تانل بزنن و الان وصل نیستن.
حتی سگارو اگر آموزش سینگ باکس رو گزاشته همش به کانفیگ json برمیگرده و کاربر معمولی یا نیمه حرفه‌ای هم سختشه بخواد خیلی توش دقیق بشه و اشکال یابی کنه.

آقا دمت گرمه 🙌🏻🌹

**Comment by aleskxyz** [comment]
> به این شکل که ما کد bash که شما نوشتی رو توی vps ایران اجرا کنیم و بهش یه کد کانکشن یا یه کانفیگ json که اطلاعات اتصال به سرور نهایی که خارج از ایرانه رو بدیم و برامون یه تانل بسازه.
> 
> من کد رو توی vps ایران اجرا کردم ، مشکلی که هست اینه که داکر ایران رو تحریم کرده و نمیشه با ip ایران ازش استفاده کرد ، من تونستم با dns دورش بزنم. ولی خب با چن بار تلاش تونستم نصبش کنم. ( کوتاه کننده لینک bitly هم کار نمیکرد. )
> 
> به نظرم این شکلی واسه خیلی از کاربرا سودمنده ، چون شما یه tui ساختی و میشه به راحتی باهاش یوزر ساخت و خیلیا نتونستن تانل بزنن و الان وصل نیستن. حتی سگارو اگر آموزش سینگ باکس رو گزاشته همش به کانفیگ json برمیگرده و کاربر معمولی یا نیمه حرفه‌ای هم سختشه بخواد خیلی توش دقیق بشه و اشکال یابی کنه.
> 
> آقا دمت گرمه 🙌🏻rose

این چیزی که شما میگید کلا میشه یه پروژه دیگه و اصلا ارتباطی با کارایی این اسکریپت نداره
