### ISSUE TITLE
Telegram robot error: OS is not supported

### ISSUE THREAD

**Issue by oneoneishere** [aleskxyz/reality-ezpz#161]
سلام وقت شما بخیر
اول از همه تشکر میکنم بابت همه زحماتی که کشیدید و همچنان میکشید، خیلی اسکریپت به درد بخور و کاربردی هستش و استفاده اش خیلی ساده و راحته
واقعا دستت طلا
من هم تابحال هیچ مشکلی ندیده بودم چه طرف سرور چه ربات تلگرام
فقط از امروز یه خطایی میگیرم
هر کامندی اجرا میکنم با ربات تلگرام میگه سیستم عامل پشتیبانی نمیشه
من ریلیس آپگرید هم نکردم
فقظ آپدیت های معمولی سیستم عامل رو انجام میدم
طرف سرور همه چی به خوبی کار میکنه
ولی طرف ربات تلگرام نه
ضمنا هیچ تغییری هم روی ربات ندادم چه سمت سرور چه تلگرام

**Comment by MohsenRN** [comment]
Same issue here without any update.

**Comment by aleskxyz** [comment]
سلام
نظر لطف شماست
الان باید مشکل برطرف شده باشه
توصیه میکنم یکبار این دستور رو هم اجرا کنید:
```
bash <(curl -sL https://bit.ly/realityez) -r
```
