### ISSUE TITLE
جایگزین ریالیتی

### ISSUE THREAD

**Issue by Zaraazad** [aleskxyz/reality-ezpz#165]
عزیز من سرور دارم ولی ssh خیلی اذیتم میکنه نپسترنت دایم قطع میشه
میشه راهنمایی کنید اسکریپت v2ray مطمین از کجا بگیرم؟ و اینکه کدوم روش الان مطمین تره برای لپ تاپ میخوام که با اکستنشن ویندسکرایب هم تداخل نکنه. چون کار گریپتو میکنم و تغییر آی پی برام ضروریه
 ریالیتی هم خیلی اذیت کرد
 ممنون
راستی اگر از سگارو و محسن عزیز خبری داری ارادت ما رو برسون

**Comment by alimajnoon1377** [comment]
گویا v2ray در همه اپراتور ها به جز همراه اول و مخابرات دچار اختلال شدیده.
