### ISSUE TITLE
Warp+ Customization

### ISSUE THREAD

**Issue by techjoyment** [aleskxyz/reality-ezpz#17]
مرسی از اسکریپت عالی
اگر بشه خودتون خودکار این آپشن رو بذارید که Warp فقط روی یک سری از سایت‌ها (اسپاتیفای، گوگل و...) فعال بشه و باقی رو با IP خود سرور باز کنه عالی میشه.

**Comment by aleskxyz** [comment]
> مرسی از اسکریپت عالی اگر بشه خودتون خودکار این آپشن رو بذارید که Warp فقط روی یک سری از سایت‌ها (اسپاتیفای، گوگل و...) فعال بشه و باقی رو با IP خود سرور باز کنه عالی میشه.

ممنون
شدنی هست ولی پیاده سازیش و تنظیمش برای کاربر عادی خیلی پیچیده میشه

**Comment by hawshemi** [comment]
https://github.com/fscarmen/warp
