### ISSUE TITLE
/usr/local/bin/docker-compose: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by RiskierSubset** [aleskxyz/reality-ezpz#170]
I'm a big noob. I'm getting this error when running the command. My gut feeling is that this is because I'm using an arm VPS. Any help is appreciated. Thanks.

**Comment by RiskierSubset** [comment]
Nevermind I forked repo and replaced the x86 download in the script with the aarch download and it worked. But now, I can't connect to it using my GUI client. 
The only thing I did was running the script and changing SNI to m.zoom.us
Any help is appreciated in fixing this issue.
I am running the script on an oracle cloud VPS with canonical ubuntu 22.04 with the ampere arm processor.

**Comment by aleskxyz** [comment]
@RiskierSubset 
Thanks for your feedback
I will look at this problem soon and update the issue

**Comment by aleskxyz** [comment]
@RiskierSubset 
I have tested the code with arm cpu and it works without problem.
I recommend to rebuild the vm and try to install again.

**Comment by RiskierSubset** [comment]
I went through the script and found that it was installing the x86 version of docker. I forked the project and replaced the x86 download link with the arm download and it worked flawlessly. Thank you for maintaining this awesome project.

**Comment by aleskxyz** [comment]
I think this commit will fix the problem:
https://github.com/aleskxyz/reality-ezpz/commit/cb6c82e92d4ac6fcfd41ab320eedc6530b9ec990
