### ISSUE TITLE
block the site

### ISSUE THREAD

**Issue by aleksan149** [aleskxyz/reality-ezpz#179]
возможно ли заблокировать доступ к определенным ресурсам в сети через прокси?

**Comment by aleskxyz** [comment]
It is possible but you needs to overwrite rule and routes of generated config based on your need. It is an advanced topic and if you don't know how to do it, it is better to don't touch.
Here is the document about how you can overwrite the configuration:

https://github.com/aleskxyz/reality-ezpz?tab=readme-ov-file#custom-configuration
