### ISSUE TITLE
Singbox Core Update

### ISSUE THREAD

**Issue by SalarAbapour** [aleskxyz/reality-ezpz#18]
سلام لطفا امکان آپدیت هسته سینگ باکس رو هم فعال کنین.ممنون

**Comment by nimaafallah** [comment]
سلام میشه لطفا ایمیلتون و داشته باشم؟ یه سوال داشتم راجع به h2

**Comment by aleskxyz** [comment]
> سلام لطفا امکان آپدیت هسته سینگ باکس رو هم فعال کنین.ممنون

سلام
نسخه سینگ باکس اپدیت شد.
به خاطر پیچیدگی این اپشن برای کاربر عادی و احتمال از کار اقتادن کامل به خاطر کانفیگ غلط اضاقه کردنش خیلی جالب نیست

**Comment by SalarAbapour** [comment]
چجوری میشه ورژن جدید رو آپدیت کرد و کانفیگ های قبلی هنوز کار بکنن؟

**Comment by aleskxyz** [comment]
> > > سلام لطفا امکان آپدیت هسته سینگ باکس رو هم فعال کنین.ممنون
> > 
> > 
> > سلام
> > نسخه سینگ باکس اپدیت شد.
> > به خاطر پیچیدگی این اپشن برای کاربر عادی و احتمال از کار اقتادن کامل به خاطر کانفیگ غلط اضاقه کردنش خیلی جالب نیست
> 
> من ایمیلم‌رو بزارم استاد زحمت بکشید [nimafallah@outlook.com](mailto:nimafallah@outlook.com)

لطفا یه issue جدید باز کنید و سوالتون رو بپرسید. ممنون میشم سوالتون در مورد این پروژه باشه. امکان پاسخ به سوالات کلی نیست

**Comment by aleskxyz** [comment]
> چجوری میشه به ورژن جدید آپدیت کرد و کانفیگ های قبلی هنوز کار بکنن؟

کد رو مجددا اجرا کنید، کانفیگهای قبلی پاک نمیشه
