### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by aleksan149** [aleskxyz/reality-ezpz#181]
У меня установлена старая версия приложения без функции создания резервной копии. Возможно ли обновить версию до последней, чтобы не слетели настроенные профили пользователей?

**Comment by aleskxyz** [comment]
Each time you run the link, it will update everything.
If you are creating user by running the script, you are already updated!
List of users and configuration are in /opt/reality-ezpz 
Create a backup from that directory and simply run the script again.
