### ISSUE TITLE
whatsapp calling issue

### ISSUE THREAD

**Issue by esmaeilbadri** [aleskxyz/reality-ezpz#19]
من چندبار روی سرور نصب کردم و همه چیز خوب کار میکنه تنها مشکلی که دارم اینه که موقع تماس واتساپ روی کانکتینگ میمونه
راه حلی هست که این مشکل رو برطرف کنم؟

**Comment by aleskxyz** [comment]
> من چندبار روی سرور نصب کردم و همه چیز خوب کار میکنه تنها مشکلی که دارم اینه که موقع تماس واتساپ روی کانکتینگ میمونه راه حلی هست که این مشکل رو برطرف کنم؟

هسته رو به xray تغییر بدید
کلاینت v2rayng رو نصب کنید
قسمت flow رو به xtls-rprx-vision-udp443 تغییر بدید و تست کنید
شاید کار کنه

**Comment by esmaeilbadri** [comment]
ممنون از راهنماییتون
ترنسپورت رو از tcp تغییر دادم و مشکل حل شد
