### ISSUE TITLE
Discord voice servers connection fails

### ISSUE THREAD

**Issue by CyrilHaritonov** [aleskxyz/reality-ezpz#191]
When entering a voice channel in Discord conncetion fails at "RTC Connecting" stage with "No route" response.
Tested using both tcp and http as a transport protocol setting in reality-ezpz. Also i have tried different clients (nekobox, v2rayN), different Discord server locations and operating systems (Windows 10, Arch Linux) and got the same error. Other apps and websites seem to be working fine.

**Comment by aleskxyz** [comment]
@CyrilHaritonov 
Can you send me some connection log from you client?
You should increase log level to see these kind of logs.

**Comment by CyrilHaritonov** [comment]
[log_nekoray.txt](https://github.com/user-attachments/files/17450056/log_nekoray.txt)
Here is some logs during the atempt to connect to Discord voice channel. Nekoray was executed with -debug option and level of logs was set to debug in core options.

**Comment by aleskxyz** [comment]
While is seems the problem is in config of the client (proxy/socks: unknown Socks version), I have updated the rulesets for server.
You can fetch new rules and test it again, maybe this time works:
```
bash <(curl -sL https://bit.ly/realityez) -r
```

**Comment by CyrilHaritonov** [comment]
I tried both with nekoray and v2rayN and got the same results with Discord. Here are some logs from the v2rayN client in the same situation as the previous. Those does not seem to indicate any error on client side.
[log2.txt](https://github.com/user-attachments/files/17465048/log2.txt)

**Comment by Xorsiphus** [comment]
I had the same problem. By the way, the problem is really on the client side, since when connecting to the voice channel from Android(v2rayNG) with the same settings, the connection is successful 🥲

**Comment by aleskxyz** [comment]
@CyrilHaritonov @Xorsiphus 
I think maybe it is because inclusion of Russia IP in bypass rules.
I have updated the rules.
Please test it again after restarting the service:
```
bash <(curl -sL https://bit.ly/realityez) -r
```

**Comment by aleskxyz** [comment]
> Unfortunately this did not help, as I already said, most likely the problem is in the client, since when connecting from the phone everything works
> 

Maybe it is related to the protocol of voice channel.
I think it is using UDP and when the client uses socks as inbound, it cannot correctly forward packets.
When you use mobile client, it is using tun interface that can handle udp packes.
I suggest you to test it with v2rayn but enable the "tun interface" option from the bottom of the window.

**Comment by CyrilHaritonov** [comment]
> enable the "tun interface" option

Enabling tun mode and adding Discord.exe to whitelist on Nekoray resolved this issue.

Thank you!
