### ISSUE TITLE
Error starting container

### ISSUE THREAD

**Issue by Xorsiphus** [aleskxyz/reality-ezpz#192]
After running the script with different parameters, the container with reality constantly writes such an error and I can not connect to the server

`FATAL[0000] start service: initialize rule-set[4]: initial rule-set: geosite-private: unsupported version: 2 | initialize rule-set[4]: initial rule-set: geoip-private: unsupported version: 2 | initialize rule-set[4]: initial rule-set: bypass: Get "https://cdn.jsdelivr.net/gh/aleskxyz/sing-box-rules@rule-set/bypass.srs": context canceled | initialize rule-set[4]: initial rule-set: block: Get "https://cdn.jsdelivr.net/gh/aleskxyz/sing-box-rules@rule-set/block.srs": context canceled | initialize rule-set[4]: initial rule-set: nsfw: Get "https://cdn.jsdelivr.net/gh/aleskxyz/sing-box-rules@rule-set/geosite-nsfw.srs": context canceled`

**Comment by aleskxyz** [comment]
@Xorsiphus 
Thanks for reporting
The issue was from the new sing-box version that generates incompatible rule-set files for old versions.
I have fixed the ruleset files and you should be able to use it restarting the script with this command:
```
bash <(curl -sL https://bit.ly/realityez) -r
```
