### ISSUE TITLE
Add the ability to block Iranian domains and IPs

### ISSUE THREAD

**Issue by MiliAxe** [aleskxyz/reality-ezpz#21]
Adding the ability to block Iranian IPs and domains would massively help the chances of the server being exposed.

Thanks for the great project.

**Comment by aleskxyz** [comment]
> 

It is already deployed in the code.
If you don't enable warp, the outgoing traffic to iran and china will be blocked
https://github.com/aleskxyz/reality-ezpz/blob/517c7a4585ebd33dab22709b1b195975eb45afc5/reality-ezpz.sh#L818
