### ISSUE TITLE
کار نکردن دستور حذف 

### ISSUE THREAD

**Issue by Mohrezaa** [aleskxyz/reality-ezpz#22]
با زدن این دستور bash <(curl -sL https://bit.ly/realityez) -u ، متاسفانه هیچ پاسخی دریاقت نمیشود و ار هم پاسخی دریافت شود باز هم پورت اشغال می باشد

**Comment by aleskxyz** [comment]
> با زدن این دستور bash <(curl -sL https://bit.ly/realityez) -u ، متاسفانه هیچ پاسخی دریاقت نمیشود و ار هم پاسخی دریافت شود باز هم پورت اشغال می باشد

مشکل برطرف شد.
مجددا تست کنید
با تشکر
