### ISSUE TITLE
error related to whiptail after updating the kernel

### ISSUE THREAD

**Issue by farzinsb** [aleskxyz/reality-ezpz#28]
hi, in centos 9 after updating the packages, the script gives this error and quits.  can you help me find what's the problem?
No match for argument: whiptail
Error: Unable to find a match: whiptail

************** log of the installation :

CentOS Stream 9 - BaseOS                                                                                                        
CentOS Stream 9 - AppStream                                                                                                             
CentOS Stream 9 - Extras packages                              
Extra Packages for Enterprise Linux 9 - x86_64                                                                                        
Extra Packages for Enterprise Linux 9 - Next - x86_64                                                                                    
Metadata cache created.
Last metadata expiration check: 0:00:02 ago on Mon 03 Jul 2023 02:25:47 PM EDT.
Package epel-release-9-5.el9.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Last metadata expiration check: 0:00:03 ago on Mon 03 Jul 2023 02:25:47 PM EDT.
No match for argument: whiptail
Error: Unable to find a match: whiptail

**Comment by aleskxyz** [comment]
Thanks for reporting.
Now it is fixed.
Try again
