### ISSUE TITLE
مشکل با منو

### ISSUE THREAD

**Issue by r-sbr90** [aleskxyz/reality-ezpz#29]
اولا ممنون بابت نوشتن این برنامه 
ولی من با بخش منو مشکل دارم و نتوانستم دستورات را وارد کنم و باید دستی وارد کنم 
مثلا هرچقدر میخواهم از حالت tcp به grpc تغییر بدهم نمی شود ok را میزنم ولی تغییر انجام نمی شود یا آدم وارد را وارد کنم هیچ جوره enable نشد ok می‌زنیم بر میگرده صفحه قبل و وقتی دوباره بازبینی میکنیم که آیا فعال شده یا نه میبینم دستور هنوز روی disable هست ربات تلگرام هم همین جور و ..... 

مجبور شدم دستی طبق آموزشی که پایین گذاشته بودی انجام دهم تا بتوانم ازش استفاده کنم 

راستی زمانی که sni را هم تغییر میدهم توی پنل نشان میدهد تغییر کرده ولی روی یوزر نه 
گفتم چون این کار را بعد از ساخت یوزر انجام دادم به مشکل خورده یوزر جدید ساختم ولی همچنان همون قبلی بود

**Comment by aleskxyz** [comment]
با دکمه بالا و پایین میتونید روی گزینه ها حرکت کنید
با دکمه space می تونید گزینه رو انتخاب کنید
با دکمه tab میتونید بین دکمه ها جا به جا بشید. وقتی رفتید روی دکمه ok، کلید space رو بزنید تا اعمال بشه
وقتی تنظیمات رو عوض کنید، تنظیمات برای همه یوزرها عوض میشه چه یوزرهای جدید چه قبلی.

**Comment by r-sbr90** [comment]
آیا می شود ی گزینه اضافه کنید که بتوان چند sni مختلف را بهش اضافه کرد 
طبق تجربه من تو reality یک sni برای یک منظقه و اپراتور خوب هست , و برای اپراتور دیگر نه (حتی توی سرعت هم تفاوت دارند)
