### ISSUE TITLE
Error: ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by AmirAghaee** [aleskxyz/reality-ezpz#3]
Hi
I ran your script on my Debian server and it installed successfully.
You can check my conf:

`vless://5b6831d1-699e-45df-8c9a-69ea3d8d2b62@38.60.202.202:443?security=reality&sni=yandex.com&pbk=vu5eJWwHEbb6ikGhyUIlItmv0viNeb_Y8MT8OMilXE4&sid=00c325cba7b979b7&type=tcp&flow=xtls-rprx-vision#reality`

But I get ERR_SSL_PROTOCOL_ERROR in my browser.
I checked with Afranet and mci internet but the problem is the same!
The url is temporary and I will remove the server as soon as possible.

**Comment by aleskxyz** [comment]
> Hi I ran your script on my Debian server and it installed successfully. You can check my conf:
> 
> `vless://5b6831d1-699e-45df-8c9a-69ea3d8d2b62@38.60.202.202:443?security=reality&sni=yandex.com&pbk=vu5eJWwHEbb6ikGhyUIlItmv0viNeb_Y8MT8OMilXE4&sid=00c325cba7b979b7&type=tcp&flow=xtls-rprx-vision#reality`
> 
> But I get ERR_SSL_PROTOCOL_ERROR in my browser. I checked with Afranet and mci internet but the problem is the same! The url is temporary and I will remove the server as soon as possible.

If you want check the functionality of TLS forwarding with your server, you should use this command:
```
curl --resolve yandex.com:443:38.60.202.202 https://yandex.com
```

**Comment by AmirAghaee** [comment]
My bad, sry
I think my server IP is dirty!
