### ISSUE TITLE
io: read\write on closed pipe

### ISSUE THREAD

**Issue by Shangulipus** [aleskxyz/reality-ezpz#30]
This is a very awesome tool. but I will always get "io: read\write on closed pipe" error
is there anything I can do to fix it?

**Comment by aleskxyz** [comment]
Thanks.
Client side error may have different nature and we cannot resolve it from server. these other ip or servers with different configuration

**Comment by AmirRahmaani** [comment]
@aleskxyz 
This one works fine. Although it might have a little more steps to setup, It works
https://github.com/HirbodBehnam/V2Ray-Installer/tree/master

**Comment by aleskxyz** [comment]
> @aleskxyz This one works fine. Although it might have a little more steps to setup, It works https://github.com/HirbodBehnam/V2Ray-Installer/tree/master

Please include a working server config

**Comment by AmirRahmaani** [comment]
> > @aleskxyz This one works fine. Although it might have a little more steps to setup, It works https://github.com/HirbodBehnam/V2Ray-Installer/tree/master
> 
> Please include a working server config

Currently I don't have a server. But I had a few servers and I made them using this. 
It was more stable than Outline

**Comment by aleskxyz** [comment]
> > > @aleskxyz This one works fine. Although it might have a little more steps to setup, It works https://github.com/HirbodBehnam/V2Ray-Installer/tree/master
> > 
> > 
> > Please include a working server config
> 
> Currently I don't have a server. But I had a few servers and I made them using this. It was more stable than Outline

Outline is another protocol. This script is mainly working on reality.

**Comment by AmirRahmaani** [comment]
> > > > @aleskxyz This one works fine. Although it might have a little more steps to setup, It works https://github.com/HirbodBehnam/V2Ray-Installer/tree/master
> > > 
> > > 
> > > Please include a working server config
> > 
> > 
> > Currently I don't have a server. But I had a few servers and I made them using this. It was more stable than Outline
> 
> Outline is another protocol. This script is mainly working on reality.

Can you add shadowsocks too?

**Comment by aleskxyz** [comment]
> > > > > @aleskxyz This one works fine. Although it might have a little more steps to setup, It works https://github.com/HirbodBehnam/V2Ray-Installer/tree/master
> > > > 
> > > > 
> > > > Please include a working server config
> > > 
> > > 
> > > Currently I don't have a server. But I had a few servers and I made them using this. It was more stable than Outline
> > 
> > 
> > Outline is another protocol. This script is mainly working on reality.
> 
> Can you add shadowsocks too?

No, this protocol is easy to detect and it will expose your server

**Comment by Erfanmv** [comment]
سلام متاسفانه بعد فعال سازی warp به این مشکل بر میخوریم با خاموش کردنش درست میشه

**Comment by aleskxyz** [comment]
> سلام متاسفانه بعد فعال سازی warp به این مشکل بر میخوریم با خاموش کردنش درست میشه

وارپ به زودی آپدیت میشه. فعلا غیرفعالش کنید

**Comment by Erfanmv** [comment]
> > سلام متاسفانه بعد فعال سازی warp به این مشکل بر میخوریم با خاموش کردنش درست میشه
> 
> وارپ به زودی آپدیت میشه. فعلا غیرفعالش کنید

ممنون
در صورت امکان اضافه کردن حالت multi gun برای grpc
در قسمت security جدا کردن malware با adult و همچنین مسدود سازی دامنه های ایرانی
و امکان ip limit هم اضافه بشه عالی میشه
و برای reality نمیشه sub domain برگشتی تعریف کرد
همچنین تشکر ویژه برای پنل خوب و سبکی که در اختیار گذاشتین

**Comment by aleskxyz** [comment]
> 

سینگ باکس multi gun رو ساپورت نمیکنه
قسمت safenet کارش همینه
سایتهای ایرانی مسدود شدن کلا
لیمیت آی پی جزو ویژگی های هسته ها نیست و باید توی اونها توسعه داده بشه
متوجه ساب دامین برگشتی نشدم
ممنون

**Comment by AmirRahmaani** [comment]
> سلام متاسفانه بعد فعال سازی warp به این مشکل بر میخوریم با خاموش کردنش درست میشه

میتونید جزئیات سرورتون رو بگید؟

**Comment by AmirRahmaani** [comment]
> > > > > > @aleskxyz This one works fine. Although it might have a little more steps to setup, It works https://github.com/HirbodBehnam/V2Ray-Installer/tree/master
> > > > > 
> > > > > 
> > > > > Please include a working server config
> > > > 
> > > > 
> > > > Currently I don't have a server. But I had a few servers and I made them using this. It was more stable than Outline
> > > 
> > > 
> > > Outline is another protocol. This script is mainly working on reality.
> > 
> > 
> > Can you add shadowsocks too?
> 
> No, this protocol is easy to detect and it will expose your server

Is this why Outline servers will stop working after a while?

**Comment by Erfanmv** [comment]
> > سلام متاسفانه بعد فعال سازی warp به این مشکل بر میخوریم با خاموش کردنش درست میشه
> 
> میتونید جزئیات سرورتون رو بگید؟ 

Ubuntu 22
Amazon
