### ISSUE TITLE
اپدیت

### ISSUE THREAD

**Issue by Saeedroshan1906** [aleskxyz/reality-ezpz#31]
اگه توی این اسکریپت بعد ساخت یوزر بتونیم واسش حجم مصرف مشخص کنیم این اسکریپت عالی میشه واسه مدیریت یوزر ها الان امکان پخش شدن کانفیگ و اتصال چندین نفر بهش هست

**Comment by aleskxyz** [comment]
متاسفانه اضافه کردن این ویژگی خیلی پیچیدگی زیادی داره و فعلا برنامه ای واسه اضافه کردنش ندارم

**Comment by mahmoodhabibi333** [comment]
> متاسفانه اضافه کردن این ویژگی خیلی پیچیدگی زیادی داره و فعلا برنامه ای واسه اضافه کردنش ندارم

درود اگر میدونید شدنی هستش به نظرم یک کانال بزنید و لایسنس درست کنید و بفروشید و قابلیت را فقط برای لایسنس دارها فعال کنید با تشکر
