### ISSUE TITLE
سرتیفیکت

### ISSUE THREAD

**Issue by cavalier-king** [aleskxyz/reality-ezpz#32]
سلام و خسته نباشید 
زمانی که سرتیفیکت میگیره و از ریالیتی خارج و روی وب سوکت قرار میدم سرور فریز میشه و دیگه منو رو بالا نمیاره

**Comment by aleskxyz** [comment]
سلام
متوجه مشکل نشدم.
یعنی شما اسکریپت رو دوباره اجرا میکنید دیگه هیچ چیزی نشون نمیده؟
به نظر میاد مشکل از سمت سرور باشه
