### ISSUE TITLE
reality verification failed

### ISSUE THREAD

**Issue by sepehrsohrabii** [aleskxyz/reality-ezpz#33]
Hi Alireza,
Hope you are good

I got an error on some of my clients. I couldn't find the reason, and I couldn't find any pattern between these devices, It's totally random. For more information, the config with the same config URL is working on my device.
The error: Get "http://cp.cloudflare.com/": reality verification failed

Thank you
Sepehr

**Comment by aleskxyz** [comment]
It seems that configs of server and client is not matched. If you had ANY change in configuration of server,  you have to reapply configuration of all clients again. So try to get config again and test it

**Comment by sepehrsohrabii** [comment]
In addition, the configs are the same as the server. Imagine a config that I'm using on my phone. I just exported it from my Nekobox. Now the problem is here, it is working on my phone and some of the clients but it doesn't work for example in my Windows or some other clients.

**Comment by aleskxyz** [comment]
try to import the exact config string that you get from the script, not the config from nekobox or other clients.

**Comment by sepehrsohrabii** [comment]
I tried as you said but again I couldn't connect through it by my Windows nekobox client, again returned: Get "http://cp.cloudflare.com/": reality verification failed

**Comment by VahidN** [comment]
Open the command line of your server and run this command:
```cmd
ping cp.cloudflare.com
```
Does it work? Probably not, because it needs `IPv6` to run.

**Comment by sepehrsohrabii** [comment]
It works as you can see in output.
The output:
PING cp.cloudflare.com(2606:4700::6810:85e5 (2606:4700::6810:85e5)) 56 data bytes
64 bytes from 2606:4700::6810:85e5 (2606:4700::6810:85e5): icmp_seq=1 ttl=55 time=5.81 ms
64 bytes from 2606:4700::6810:85e5 (2606:4700::6810:85e5): icmp_seq=2 ttl=55 time=5.44 ms
64 bytes from 2606:4700::6810:85e5 (2606:4700::6810:85e5): icmp_seq=3 ttl=55 time=5.43 ms
64 bytes from 2606:4700::6810:85e5 (2606:4700::6810:85e5): icmp_seq=4 ttl=55 time=5.51 ms
64 bytes from 2606:4700::6810:85e5 (2606:4700::6810:85e5): icmp_seq=5 ttl=55 time=5.41 ms
64 bytes from 2606:4700::6810:85e5 (2606:4700::6810:85e5): icmp_seq=6 ttl=55 time=5.38 ms
64 bytes from 2606:4700::6810:85e5 (2606:4700::6810:85e5): icmp_seq=7 ttl=55 time=5.45 ms
64 bytes from 2606:4700::6810:85e5 (2606:4700::6810:85e5): icmp_seq=8 ttl=55 time=5.34 ms
^C
--- cp.cloudflare.com ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7011ms

**Comment by sepehrsohrabii** [comment]
But in client side again I got this error:
INFO[0000] sing-box started (0.00s)
INFO[0000] outbound/vless[proxy]: outbound connection to cp.cloudflare.com:80
[[VLESS] Sepi] test error: Get "http://cp.cloudflare.com/": reality verification failed

**Comment by sepehrsohrabii** [comment]
For more addition it is now working on my android phone(NekoBox). but It doesn't work on my laptop(NekoRay).

**Comment by sepehrsohrabii** [comment]
I installed v2rayN and now the nekoray is working :||

**Comment by AmirSaeedGolbazi** [comment]
Same problem tried everything works on android nothing on pc tried both nekoray and v2rayn clients

**Comment by AmirSaeedGolbazi** [comment]
> I installed v2rayN and now the nekoray is working :||

was it solved for you?

**Comment by aleskxyz** [comment]
@sepehrsohrabii @AmirSaeedGolbazi 
I have tested the configs on v2rayn and nekoray and both of them are working.
Kepp in mind only xray and sing-box cores are working in these tools, other cores such as v2ray and ... are not compatible. So check your configuration.
If you want to use v2rayN, use v6.27 https://github.com/2dust/v2rayN/releases/tag/6.27

**Comment by bijanpiri** [comment]
Sometimes I have the same error with the same connection. it comes and goes by itself and I do not have any idea

**Comment by bijanpiri** [comment]
Finally I found the reason for this issuse: the wrong windows system time is the source of this problem.

I guess TLS use system time in encryption and we get reality verification failed whenever out system time is different from our location.

**Comment by netrolite** [comment]
> Finally I found the reason for this issue: the wrong windows system time is the source of this problem.
> 
> 
> 
> I guess TLS use system time in encryption and we get reality verification failed whenever out system time is different from our location.

Thank you so much. This fixed it instantly
