### ISSUE TITLE
Problem with NAT vps

### ISSUE THREAD

**Issue by mfat** [aleskxyz/reality-ezpz#34]
My nat server only has a few ports available. 
443 is not available. 
How can I use letsencrypt (not reality) with port 1207?
It didn't work with the attached config.
![Screenshot_20230706-124433-418](https://github.com/aleskxyz/reality-ezpz/assets/423263/b222d959-5938-44df-b242-c4fede65265c)

Thanks much

**Comment by aleskxyz** [comment]
You cannot use letsencrypt with natvps because port 80 must be free for it and this port is not available for natvps servers.

**Comment by mfat** [comment]
Yes but if I use IPv6 all ports are open. I've mapped ipv6 address of the server to a domain name in Cloudflare and successfully got a let's encrypt certificate.
