### ISSUE TITLE
Feature request: batter names for generated configs

### ISSUE THREAD

**Issue by mfat** [aleskxyz/reality-ezpz#36]
This script is a piece of art but the naming schema is too generic.
Every config is saved as reality-ezpz.

I suggest using the server ip or domain name + protocol for better looking names.

**Comment by aleskxyz** [comment]
> This script is a piece of art but the naming schema is too generic. Every config is saved as reality-ezpz.
> 
> I suggest using the server ip or domain name + protocol for better looking names.

Thanks
Notice that the latest applied configuration is the only active config. When you change the config of server, you need to get the new configuration of each user again.
So naming the users by the type of configs is meaningless!

**Comment by mfat** [comment]
Yeah you're right. Thanks!
