### ISSUE TITLE
 driver failed programming external

### ISSUE THREAD

**Issue by Aramcodewp** [aleskxyz/reality-ezpz#4]
I ran your script but I get the following error. Please advise on this.
Thanks
"Error response from daemon: driver failed programming external connectivity on endpoint reality-xray-1 (c26892f8f0e12254596e3c38f21653ef7f10c540035e2a43594abead4a401725): Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use"

**Comment by aleskxyz** [comment]
> I ran your script but I get the following error. Please advise on this. Thanks "Error response from daemon: driver failed programming external connectivity on endpoint reality-xray-1 (c26892f8f0e12254596e3c38f21653ef7f10c540035e2a43594abead4a401725): Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use"

It seems another process is listening on port 443. You need to be sure port 80 and 443 is free before running this script.
