### ISSUE TITLE
error : address already in use

### ISSUE THREAD

**Issue by mhg777** [aleskxyz/reality-ezpz#40]
داداش من ته پیامی که برام میاد اینطوریه 

میشه کمکم کنی حلش کنم؟

[+] Running 2/0
 ✔ Container reality-ezpz-engine-1  Removed                                                                                                                                                     0.0s
 ✔ Network reality-ezpz_reality     Removed                                                                                                                                                     0.1s
Warning: No resource found to remove for project "reality-ezpz".
[+] Running 1/2
 ✔ Network reality-ezpz_reality     Created                                                                                                                                                     0.1s
 ⠿ Container reality-ezpz-engine-1  Starting                                                                                                                                                    0.4s
_Error response from daemon: driver failed programming external connectivity on endpoint reality-ezpz-engine-1 (433863e52b15df58b3d23be2c7d775ead7dd2b0c63440d402bc1dfe9c4cd4a51): Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use_

**Comment by mfat** [comment]
یه سرویس از قبل روی پورت ۴۴۳ داری. اینو بزن ببین چیه
`netstat -plnt`

**Comment by aleskxyz** [comment]
اگر پنل یا برنامه ای نصب دارید که داره از پرت ۴۴۳ استفاده میکنه یا برنامه رو حذف کنید یا اسکریپت رو با پرتی به غیر از ۴۴۳ اجرا کنید
