### ISSUE TITLE
عدم اتصال

### ISSUE THREAD

**Issue by xmeysamx** [aleskxyz/reality-ezpz#42]
سلام وقت بخیر مهندس
اولا جا داره تشکر کنم از تلاشاتون ثانیا بعد اینکه کانفیگ ساخته شد و تو نکو باکس وارد کردم سرعت در حد صفر هست آی پی سرور سالم هس و راحت کانکت میشه توی استکهلم هس سرور - تنظیمات دیگه هم دیفالت هستن با نت ایرانسل و مخابرات هم امتحان کردم به نظرتون از چی میتونه باشه؟ پیشاپیش خیلی ممنون

**Comment by VahidN** [comment]
براي بررسي سالم بودن IP از اين سايت‌ها استفاده كنيد كه با استفاده از سرورهاي داخل ايران، وضعيت IP رو مشخص مي‌كنند:
https://check-host.net/
https://www.host-tracker.com/en/ic/ping-test  --> set the location to Iran

**Comment by Varooneh** [comment]
با سلام و احترام
من هم مشکل عدم اتصال دارم، آی پی رو هم با لینک هایی که آقای نصیری فرمودن تست کردم سالم بود، طبق راهنما و تنظیمات پیش فرض هم نصب کردم ولی متاسفانه متصل نمیشه، ممنون میشم راهنماییم کنید.

**Comment by VahidN** [comment]
در قسمت لاگ برنامه‌ي v2rayng چه چيزي مشاهده مي‌كنيد؟ خطا و علت دقيق عدم اتصال رو اونجا مي‌تونيد مشاهده كنيد.

**Comment by aleskxyz** [comment]
ممنون @VahidN جان به خاطر کمکت.
من در مورد تنظیماتی که باعث بشه کیفیت خوبی بگیرید نمیتونم نظر بدم چون شبکه به شبکه متفاوته و باید تست کنید.
چیزی که میتونم با اطمینان بالا بگم اینه که اسکریپت حداقل با تنظیمات دیفالت باید کار کنه. اگه متصل نمیشید یا کلاینت شما مشکل داره یا شبکه ای که باهاش متصل میشید.
