### ISSUE TITLE
Feature request: custom uuid 

### ISSUE THREAD

**Issue by mehrabmp** [aleskxyz/reality-ezpz#44]
Hi, can you add an option to change the user uuid?
Anyway, thanks for the great script

**Comment by aleskxyz** [comment]
You can delete and recreate the user if you want to change uuid
If you want to enter your uuid you can edit /opt/reality-ezpz/users file manualy, then you need to run script to generate configs for that users

**Comment by mehrabmp** [comment]
That's what I was looking for
tnx
