### ISSUE TITLE
 (Warp) مشکلی در تنظیمات 

### ISSUE THREAD

**Issue by NoRRt** [aleskxyz/reality-ezpz#47]
سلام و خسته نباشید بابت زحماتی که برای این اسکریپت میکشید  ..
یک مشکلی  در Warp وجود داره که وقتی Enable  میزنید . 
![Screenshot 2023-07-10 144736](https://github.com/aleskxyz/reality-ezpz/assets/4822035/fe590d84-aee5-4e1a-8bb7-0b18e5fc340c)
چیزی نشون نمیده

**Comment by aleskxyz** [comment]
به نظر میاد ای پی سرور شما از طرف کلادفلیر محدود شده.
دلیلش رو نمیدونم ولی برای بعضیا اینجوری شده
میتونید با یه سرور دیگه تست کنید

**Comment by Asad099h** [comment]
برای من امروز اینجوری شد دقیقا بعد از اینکه اومدم لایسنس رو عوض کنم. روی هر دو سرورم از کار افتاد. شاید بخاطر آپدیت اخیر وارپ باشه.

**Comment by aleskxyz** [comment]
> برای من امروز اینجوری شد دقیقا بعد از اینکه اومدم لایسنس رو عوض کنم. روی هر دو سرورم از کار افتاد. شاید بخاطر آپدیت اخیر وارپ باشه.

مشکل حل شد
مجددا اسکریپت رو اجرا کنید

**Comment by Asad099h** [comment]
> > برای من امروز اینجوری شد دقیقا بعد از اینکه اومدم لایسنس رو عوض کنم. روی هر دو سرورم از کار افتاد. شاید بخاطر آپدیت اخیر وارپ باشه.
> 
> مشکل حل شد مجددا اسکریپت رو اجرا کنید

عالییییی تشکر
