### ISSUE TITLE
Feature request: Amnezia integration 

### ISSUE THREAD

**Issue by mfat** [aleskxyz/reality-ezpz#49]
Please fork Amnezia and add support for your script for super easy deployment. https://github.com/amnezia-vpn

Amnezia uses docker containers so it shouldn't be too hard to integrate.

**Comment by aleskxyz** [comment]
They should integrate this script in their code, not me!

**Comment by mfat** [comment]
Already [Asked them](https://github.com/amnezia-vpn/amnezia-client/issues/258) to do so :)

**Comment by aleskxyz** [comment]
Thank you but it seems that project is not getting update anymore!

**Comment by mfat** [comment]
It is getting updates. Plrase see this repo:
https://github.com/amnezia-vpn/amnezia-client
