### ISSUE TITLE
سلام کد بسیار خوبیه فقط کاش قابلیت جنریت بیش از یک کانفیگ ریالیتی رو داشت 

### ISSUE THREAD

**Issue by armanem2** [aleskxyz/reality-ezpz#5]
سلام کد بسیار خوبیه فقط کاش قابلیت جنریت بیش از یک کانفیگ ریالیتی رو داشت  مثلا یکی همراه اول یکی ایرانسل روی دوپورت بازم منونم

**Comment by aleskxyz** [comment]
> سلام کد بسیار خوبیه فقط کاش قابلیت جنریت بیش از یک کانفیگ ریالیتی رو داشت مثلا یکی همراه اول یکی ایرانسل روی دوپورت بازم منونم

پیچیدگی این موضوع زیاده چون کد سمت کاربر فقط به یه دامنه وصل میشه و عوض کردن پورت به غیر از ۴۴۳ هم کار اشتباهیه
