### ISSUE TITLE
 تعیین حجم برای کاربران

### ISSUE THREAD

**Issue by shahab3z-web** [aleskxyz/reality-ezpz#51]

**Comment by shahab3z-web** [comment]
سلام خسته نباشید ببخشید میتونید قابلیت تعیین حجم برای کاربران رو هم اضافه کنید سپاس

**Comment by aleskxyz** [comment]
سلام
این قابلیت پیچیده و زمانبری هست و فعلا برنامه ای برای اجراش ندارم متاسفانه
