### ISSUE TITLE
Client For Linux

### ISSUE THREAD

**Issue by saeidshirazi** [aleskxyz/reality-ezpz#53]
سلام ببخشید من چجوری میتونم از کانفیگ reality روی لینوکسم استفاده کنم؟!
کلاینت ها معمولا جواب نمیدن روی لینوکس روشی داره!؟ میشه نحوه استفاده روی لینوکسشم بزارید ممنون

**Comment by aleskxyz** [comment]
اگه از دسکتاپ لینوکس استفاده میکنید میتونید از nekoray استفاده کنید
https://github.com/MatsuriDayo/nekoray/releases/download/3.9/nekoray-3.9-2023-06-27-linux-x64.AppImage

**Comment by saeidshirazi** [comment]
نصب کردم جواب نمیده ترافیک رد نمیشه متاسفانه...

**Comment by aleskxyz** [comment]
داکیومنتهاشو بخونید
یه مود پروکسی داره اونو فعال کنید و با ساکس بهش وصل بشید
