### ISSUE TITLE
ios 12 reality support

### ISSUE THREAD

**Issue by hamedefatian** [aleskxyz/reality-ezpz#56]
hi dear
which app support rality with ios 12
dose fairvpn can use?

سلام بر شما دوست گرامی
ضمن تشکر و قدردان از زحمات شما
گوشی های آیفون قدیمی که از ios 12 نصب دارن چه برنامه میتونیم نصب کنیم که ریلتی ساپورت کنه؟
اطلاعی دارید؟

**Comment by VahidN** [comment]
https://apps.apple.com/us/app/v2box-v2ray-client/id6446814690
https://apps.apple.com/us/app/streisand/id6450534064

**Comment by hamedefatian** [comment]
> 
ممنون
ولی اینا جفتشون حداقل ios 14 نیاز دارن
من دنبال ios 12 هستم
