### ISSUE TITLE
new inbounds

### ISSUE THREAD

**Issue by johnWinchester01** [aleskxyz/reality-ezpz#60]
Hi how can we add other inbounds like shadowsocks to sing-box?
I added the following code to engine config but i can't seem to connect to it
{
	"type": "shadowsocks",
	"tag": "shadowsocks-in",
	"listen": "::",
        "listen_port": 5353,
	"method": "chacha20-ietf-poly1305",
	"password": "testPassword"
},

**Comment by aleskxyz** [comment]
You are not supposed to edit configs because each time you run the script, the configs will be overwritten.
The sing-box is running from a docker container, you also need to open ports in docker-compose.yml if you want to listen on a new port.

**Comment by johnWinchester01** [comment]
i don't think opening ports alone would do me any good beacuase i think haproxy also should be configured also, right?
