### ISSUE TITLE
Custom rules for warp traffic

### ISSUE THREAD

**Issue by mehrabmp** [aleskxyz/reality-ezpz#61]
Hi
Is it possible to define custom rules to pass traffic through warp?
I want to pass google and some other geosites through warp and still block Iran ips and sites
I know how to do this in the config file but don't know if it will cause problems in the script.
It would be great if you could add an option for this to the menu.
Thanks

**Comment by aleskxyz** [comment]
Now you can apply you custom configuration if you are familiar with configuration 
https://github.com/aleskxyz/reality-ezpz#custom-configuration
