### ISSUE TITLE
show core versions and enable for use pre-release core

### ISSUE THREAD

**Issue by AkramiPro** [aleskxyz/reality-ezpz#62]
سلام ممنون از اسکریپت خوبتون
2 تا مورد اگر میشه اضافه کنید :

1. نسخه هسته که داره استفاده میشه رو بزنه توی منو
2. بتونیم انتخاب کنیم که از کدوم نسخه هسته استفاده کنه مثلا sing-box نسخه pre-release هم داره

ممنون

**Comment by aleskxyz** [comment]
میشه نسخه هسته رو اضافه کرد
ولی امکان تغییر نسخه هسته احتمال کانفیگ اشتباه از سمت کاربر و از کار افتادن اسکریپت رو زیاد میکنه.
تمام تلاش اسکریپت اینه که حتی در صورت اشتباه کاربر هم کار کنه
