### ISSUE TITLE
I'm facing an error in the installation process

### ISSUE THREAD

**Issue by armin567ip** [aleskxyz/reality-ezpz#67]
root@armin567ip:~# bash <(curl -sL https://bit.ly/realityez)
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "proc" to rootfs at "/proc": mount proc:/proc (via /proc/self/fd/6), flags: 0xe: permission denied: unknown.

**Comment by aleskxyz** [comment]
سلام
مشخصات سرورتون چیه؟
سیستم عامل و ...
از کجا خریدید؟

**Comment by armin567ip** [comment]
> سلام
> مشخصات سرورتون چیه؟
> سیستم عامل و ...
> از کجا خریدید؟

I could get it fixed by using sudo apt update instead of apt update. But the new problem is after generating the vless. It's not working.
There is another script on Github by Sonyacore called vmess-deploy

**curl https://raw.githubusercontent.com/SonyaCore/vmess-deploy/main/deploy.sh | sudo bash**

This one is working just fine for me. But yours isn't.

Ubuntu 20 x64, 2GB of Ram, 2 CPU cores, ProHoster

**Comment by aleskxyz** [comment]
> > سلام
> > مشخصات سرورتون چیه؟
> > سیستم عامل و ...
> > از کجا خریدید؟
> 
> I could get it fixed by using sudo apt update instead of apt update. But the new problem is after generating the vless. It's not working. There is another script on Github by Sonyacore called vmess-deploy
> 
> **curl https://raw.githubusercontent.com/SonyaCore/vmess-deploy/main/deploy.sh | sudo bash**
> 
> This one is working just fine for me. But yours isn't.
> 
> Ubuntu 20 x64, 2GB of Ram, 2 CPU cores, ProHoster

that script is using vmess not vless on v2ray core, not xray or sing-box which are completely different things

**Comment by armin567ip** [comment]
> > > سلام
> > > مشخصات سرورتون چیه؟
> > > سیستم عامل و ...
> > > از کجا خریدید؟
> > 
> > I could get it fixed by using sudo apt update instead of apt update. But the new problem is after generating the vless. It's not working. There is another script on Github by Sonyacore called vmess-deploy
> > 
> > **curl https://raw.githubusercontent.com/SonyaCore/vmess-deploy/main/deploy.sh | sudo bash**
> > 
> > This one is working just fine for me. But yours isn't.
> > 
> > Ubuntu 20 x64, 2GB of Ram, 2 CPU cores, ProHoster
> 
> that script is using vmess not vless on v2ray core, not xray or sing-box which are completely different things

So what's the solution?
I wanna get your script to work.

**Comment by mamadoof** [comment]
دقیقا منم همین مشکل رو دارم
همون سروری که معرفی کردید 50 درصد تخفیف داره همونو خریدم من

**Comment by armin567ip** [comment]
> دقیقا منم همین مشکل رو دارم
> همون سروری که معرفی کردید اینجا
> prohoster
> اینو خریدم

داش راه حلشو فهمیدم. این کلا جواب نمیده با این سرور. باید پنل بالا بیاری. اگه بلد نیستی. دیسکوردت رو بده کمکت میکنم ❤👍

**Comment by mamadoof** [comment]
> > دقیقا منم همین مشکل رو دارم
> > همون سروری که معرفی کردید اینجا
> > prohoster
> > اینو خریدم
> 
> داش راه حلشو فهمیدم. این کلا جواب نمیده با این سرور. باید پنل بالا بیاری. اگه بلد نیستی. دیسکوردت رو بده کمکت میکنم ❤👍


مرسی داداش
من روش پلن علیرضایی رو نصب کردم بدک نیست فعلا خوبه
اگه پنل شما بهتره که شما نصب کنید
اگه دستور خاصی که بلدم انجام بدم خودم
