### ISSUE TITLE
مشکل نصب

### ISSUE THREAD

**Issue by mamadoof** [aleskxyz/reality-ezpz#68]
سلام موقع نصب میخاد تموم شه اخرش اینو میده مشکل چیه؟ 

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "proc" to rootfs at "/proc": mount proc:/proc (via /proc/self/fd/6), flags: 0xe: permission denied: unknown.
ERRO[0002] error waiting for container:

**Comment by aleskxyz** [comment]
اینجا پیگیری کنید
https://github.com/aleskxyz/reality-ezpz/issues/67
