### ISSUE TITLE
حجم مصرفی یوزرها 

### ISSUE THREAD

**Issue by Danialsafarli** [aleskxyz/reality-ezpz#69]
سلام علیرضا جان. آیا در تنظیمات قسمتی برای تعیین میزان حجم مصرفی یوزرها وجود داره؟
تشکر

**Comment by Danialsafarli** [comment]
![image](https://github.com/aleskxyz/reality-ezpz/assets/95703991/634d2a10-7403-4f6a-8c1c-c11c3f610111)

**Comment by aleskxyz** [comment]
سلام
کامند رو با دقت وارد کنید! جای پرانتز عدد زدید

**Comment by Danialsafarli** [comment]
بله تصحیح کردم باز با پیغام قبلی مواجه شدم
![image](https://github.com/aleskxyz/reality-ezpz/assets/95703991/f648963f-7fab-4097-b370-ad5482122358)

**Comment by Danialsafarli** [comment]
ممنون از شما.درست شد. آیا در تنظیمات قسمتی برای تعیین میزان حجم مصرفی یوزرها وجود داره؟

**Comment by aleskxyz** [comment]
ممنون
نه وجود نداره
