### ISSUE TITLE
docker run -q

### ISSUE THREAD

**Issue by mmirmoosavi** [aleskxyz/reality-ezpz#7]
خط ۱۷۱ این دستور docker run -q ارور داره

**Comment by aleskxyz** [comment]
> خط ۱۷۱ این دستور docker run -q ارور داره

فیکسش کردم
https://github.com/aleskxyz/reality-ezpz/commit/9706b4ef7584b1cd6758ddfd486ac69201596940
ولی به خاطر نسخه قدیمی داکری که قبلا نصب کردید احتمالا دستور docker compose اجرا نشه

**Comment by mmirmoosavi** [comment]
> > خط ۱۷۱ این دستور docker run -q ارور داره
> 
> فیکسش کردم [9706b4e](https://github.com/aleskxyz/reality-ezpz/commit/9706b4ef7584b1cd6758ddfd486ac69201596940) ولی به خاطر نسخه قدیمی داکری که قبلا نصب کردید احتمالا دستور docker compose اجرا نشه

ممنونم
