### ISSUE TITLE
Vmess reality

### ISSUE THREAD

**Issue by misagh72** [aleskxyz/reality-ezpz#70]
با سلام میخواستم ببینم با توجه به اینکه singbox از vmess reality پیشتیبانی میکنه امکان اضافه کردنش هست یا نه

**Comment by aleskxyz** [comment]
> با سلام میخواستم ببینم با توجه به اینکه singbox از vmess reality پیشتیبانی میکنه امکان اضافه کردنش هست یا نه

چون xray ساپورت نمیکنه نمیشه اضافه کرد. تفاوتی هم توی نتیجه نهایی نداره
