### ISSUE TITLE
error

### ISSUE THREAD

**Issue by miladmsv91** [aleskxyz/reality-ezpz#71]
سلام علیرضا جان 
من کد رو اجرا میکنم این ارور رو میده 
چطور رفعش کنم؟
![Screenshot 2023-08-06 182823](https://github.com/aleskxyz/reality-ezpz/assets/141570630/4df1bba1-0b17-4a19-8023-14b944afcf44)

**Comment by aleskxyz** [comment]
> برای منم همین ارور رو ی ده

سرور رو پاک کنید و دوباره بسازید

**Comment by aleskxyz** [comment]
احتمالا یه مشکل سمت ifconfig.io هست
دوباره تست کنید
