### ISSUE TITLE
graphical Interface

### ISSUE THREAD

**Issue by Atasharef1381** [aleskxyz/reality-ezpz#75]
Hi Alireza , I really appreciate your great work on reality-ezpz , but if possible , contribute with other programmers and start creating a GUI and also a better user management system , most of my friends abuse the config I've given them by sharing it to a lot of people , please keep in mind , we support you and all contributors to this project , and we thank you all .
Yours Sincerely 
cipherx .

**Comment by aleskxyz** [comment]
> Hi Alireza , I really appreciate your great work on reality-ezpz , but if possible , contribute with other programmers and start creating a GUI and also a better user management system , most of my friends abuse the config I've given them by sharing it to a lot of people , please keep in mind , we support you and all contributors to this project , and we thank you all . Yours Sincerely cipherx .

Thanks for your kind works,
Actually this is a script that other developers can use it as the core of different products. It should be easy to create web interface for it and I welcome contributions!
About the accounting, it is a complex project and needs time for development. Unfortunately I don't have time to spent on it for now.
Regards
