### ISSUE TITLE
I can't open Iranian websites.

### ISSUE THREAD

**Issue by bestmimbrand** [aleskxyz/reality-ezpz#79]
I can't open Iranian websites.
How can I fix this?
(I think you did this to prevent filtering).
But I need to disable this feature.

Thank  you very much.

**Comment by aleskxyz** [comment]
You can configure your client to use direct connection for ips with Iran destination.
Each client has its own configuration.
Read its manual.
You need to mention "geoip:ir" in the rule configuration
