### ISSUE TITLE
Add blocking of Iranian hosted websites

### ISSUE THREAD

**Issue by free-the-internet** [aleskxyz/reality-ezpz#8]
Please add blocking of Iranian hosted websites/IPs (also Iranian ads) to avoid exposing server IP to censor.
FYI: This method is used in China by GFW, We don't know about Iran as far as I know, but for the sake of safety, I think it's necessary.
Thanks for your really EZ script.

**Comment by aleskxyz** [comment]
> Please add blocking of Iranian hosted websites/IPs (also Iranian ads) to avoid exposing server IP to censor. FYI: This method is used in China by GFW, We don't know about Iran as far as I know, but for the sake of safety, I think it's necessary. Thanks for your really EZ script.

Thanks for the advice.
If you didn't enable warp, this script will block outgoing traffic to Iranian and Chinese IPs:
https://github.com/aleskxyz/reality-ezpz/blob/master/reality-ezpz.sh#L482
Regards
