### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by master88wi** [aleskxyz/reality-ezpz#80]
ipv6 support

**Comment by aleskxyz** [comment]
It is not polite way to start a discussion!
If you don't know English you can use tools like chatgpt to help you for writing your request.
Regarding to the ipv6 support,
It is very complex in implementation alongside with ipv4
This script is designed to make everything easy for users that even don't know what the "IP" is.
Becasue this script is useing docker for managing the workload, it adds another layer of complexity in network stack.
It is not as easy as enabling the ipv6.
If you want to use ipv6, you can get the configuration from this script and run your own service standalone or use other methods that supports ipv6
Regards

**Comment by master88wi** [comment]
so what's the problem?
docker can also work in ipv6.
I'm just giving an idea.
I respect you.

**Comment by master88wi** [comment]
https://www.docker.com/blog/docker-hub-registry-ipv6-support-now-generally-available/
