### ISSUE TITLE
Feature request: Multiple SNIs

### ISSUE THREAD

**Issue by parsamrrelax** [aleskxyz/reality-ezpz#81]
Ability to add multiple snis would be a nice add. Hiddify has something like this I believe.

**Comment by aleskxyz** [comment]
Yes it would be good but sing-box does not support multiple sni
Also in client side we cannot use multiple sni.

**Comment by aleskxyz** [comment]
> > Yes it would be good but sing-box does not support multiple sni Also in client side we cannot use multiple sni.
> 
> I believe making multiple configurations with multiple snis is possible. The general picture would be adding multiple snis in ezpz menu seperated by commas. Different configs generated for each user with each sni.

Sing-box only support one server in reality:
https://sing-box.sagernet.org/configuration/shared/tls/#reality-fields
