### ISSUE TITLE
pls read you email and telegram

### ISSUE THREAD

**Issue by master88wi** [aleskxyz/reality-ezpz#82]
pls read you email and telegram

**Comment by aleskxyz** [comment]
Hi
I only answers the github issue.
Some issues are open because it needs time to investigate.
Be patient.

**Comment by master88wi** [comment]
I understand. I just threw you a lot of useful information
, some of it cannot be fully published here

**Comment by aleskxyz** [comment]
Thanks for your attention 
This is a public repository for an open source project.
Also this is a deployment script that only installs some ready to use tools.
So nothing can be confidential here. If you are afraid of your identity, you can open an issue with anonymous account.
