### ISSUE TITLE
از کار افتادن کانفیگ ها با افزایش یوزر

### ISSUE THREAD

**Issue by mimabbasi** [aleskxyz/reality-ezpz#83]
سلام دوست عزیز
از زحمات شما بابت این اسکریپت فوق العاده سپاسگزارم
اما از چند روز گذشته وقتی تعداد یوزرها به  20 یا 30 میرسن تمام کانفیگ ها از کار میوفتن. با اینکه آی پی سرور سالم  و دامنه و یا ساب دامنه هم سالمه.
میشه راهنمایی کنید که مشکل از کجا میتونه باشه و چجور میتونم جلوی این مشکل رو بگیرم؟

**Comment by aleskxyz** [comment]
سلام
فکر میکنم منابع سرورتون کمه
من همین الان هزارتا یوزر ساختم و مشکلی وجود نداشت

**Comment by mimabbasi** [comment]
عذر میخوام میشه در مورد منابع سرور بیشتر توضیح بدید؟
یا اینکه باید چکار کنم که منابع سرور بیشتر بشه؟
منظورتون از منابع، مشخصات سخت افزاری سرور هست؟ اگه اینه چه مشخصاتی پیشنهاد میدید؟

**Comment by aleskxyz** [comment]
منظورم میزان رم و cpu هست

**Comment by mimabbasi** [comment]
عذر میخوام که مجدد پیام میدم
براساس آزمون و خطا و تجربه ای که دارید. برای ساخت حدود 100 یوزر، حدودا به چه مقدار رم و cpu نیاز هست؟؟؟
تقریبی هم بگید ممنون میشم

**Comment by aleskxyz** [comment]
حداقل دو گیگ رم

**Comment by mimabbasi** [comment]
سپاسگزارم ولی برای محکم کاری یه سرور  با 8 گیگ رم و 4xCPU گرفتم
جسارتا میدونم دغدغه های شما خیلی زیاده  و مسائل مهمتری رو دنبال میکنید
ولی بنطرتون با این مقدار 200 کاربر رو ساپورت میکنه؟

**Comment by aleskxyz** [comment]
بستگی داره به میزان مصرف
میتونید میزان مصرف cpu رو با دستور زیر ببینید:
```
top -bn 1 | awk '/Cpu/ {print 100 - $8"%"}'
```
مصرف رم رو هم با دستور زیر:
```
free | grep Mem | awk '{print ($3/$2) * 100.0"%"}'
```

**Comment by mimabbasi** [comment]
سپاسگزارم دوست عزیز
