### ISSUE TITLE
تفاوت پنل ها

### ISSUE THREAD

**Issue by jamiekarvans** [aleskxyz/reality-ezpz#84]
با سلام تشکر بابت ضحماتتون و اسکریپت شما چه تفاوتی با پنل x-ui دوستان  مثلا اقای ثنایی داره؟
چون پنل های دیگه دارای صفحه کاربری هستن و اپشن های بیشتر خواستم ببینم نکته خاصی هست مثلا با اسکریپت شما شانس فیلتر شدن کمتر میشه؟
و اینکه ایا قابلیت گزاشتن تاریخ قطع شدن کاربرا وجود داره؟

**Comment by aleskxyz** [comment]
سلام

- مصرف منابعش حداقله. سایر پنلها حداقل یه گیگ رم برای خود پنل میخوان
- امکان کشف سرور به خاطر نداشتن رد پا توی وب به حداقل میرسه
- امکان هک سرور وجود نداره چون هیچ راهی به بیرون باز نیست
- خیلی سریعتر نصب میشه
- هیچ بسته ای به جز داکر روی سرور نصب نمیکنه و سرور رو کثیف نمیکنه
- کد خیلی ساده و شفافی داره و دیگران میتونن در مورد جزییات کار کردنش نظر بدن و از امنیتش مطمین بشن
- موارد امنیتی برای کشف نشدن سرور توش رعایت شده. اگه میبینید بعضی ویژگیها توی این اسکریپت وجود نداره به خاطر مسایل امنیتیه وگرنه میشد همه پروتکلها رو در کنار هم ارایه داد

هدف این اسکریپت راه اندازی سریع یه سرور شخصی برای افراد و اعضا خانواده و نزدیکانه واسه همین مدیریت دقیق کاربران خیلی مورد توجه نیست.
جواب سوالتون هم خیر هست

**Comment by mahmoodhabibi333** [comment]
> سلام
> 
>     * مصرف منابعش حداقله. سایر پنلها حداقل یه گیگ رم برای خود پنل میخوان
> 
>     * امکان کشف سرور به خاطر نداشتن رد پا توی وب به حداقل میرسه
> 
>     * امکان هک سرور وجود نداره چون هیچ راهی به بیرون باز نیست
> 
>     * خیلی سریعتر نصب میشه
> 
>     * هیچ بسته ای به جز داکر روی سرور نصب نمیکنه و سرور رو کثیف نمیکنه
> 
>     * کد خیلی ساده و شفافی داره و دیگران میتونن در مورد جزییات کار کردنش نظر بدن و از امنیتش مطمین بشن
> 
>     * موارد امنیتی برای کشف نشدن سرور توش رعایت شده. اگه میبینید بعضی ویژگیها توی این اسکریپت وجود نداره به خاطر مسایل امنیتیه وگرنه میشد همه پروتکلها رو در کنار هم ارایه داد
> 
> 
> هدف این اسکریپت راه اندازی سریع یه سرور شخصی برای افراد و اعضا خانواده و نزدیکانه واسه همین مدیریت دقیق کاربران خیلی مورد توجه نیست. جواب سوالتون هم خیر هست

درود بر شما اگر امکان داره دو بخشی کنید یعنی یه قسمت برای کسانی که پنل میخواهند به صورت وب یا شبیه xui یه قسمت هم همینی که الان هستش به نظرم خیلی خوب میشه
