### ISSUE TITLE
Allows us to associate a Telegram ID with each user 

### ISSUE THREAD

**Issue by alikarami010** [aleskxyz/reality-ezpz#89]
Introducing a feature that allows us to associate a Telegram ID with each user would be highly beneficial. Moreover, in the event of an IP change or any other issue, having a Telegram bot generate a new URI within the system would be a valuable addition.

**Comment by aleskxyz** [comment]
Hi
I recommend to use subdomain instead of ip so you can use valid certificates of letrencrypt and in case of chamge in ip you only need to update subdomain.
You can use telegram id instead for the name of users
