### ISSUE TITLE
قطع شدن بعضی از یوزرها

### ISSUE THREAD

**Issue by mimabbasi** [aleskxyz/reality-ezpz#93]
سلام دوست عزیز 
امروز با یه مشکل عجیب برخوردم که بعضی از افراد اطلاع دادن که اتصالشون قطع شده
ولی بنده سرور رو چک کردم اوکی بود، حتی با کانفیگ همون افرادی که قطع شده بودن هم وصل شدم و پینگ و سرعت خوب خوبی داشت
بنظرتون مشکل از کجا میتونه باشه؟؟

**Comment by aleskxyz** [comment]
سلام
اصولا برای حل مشکل نمیشه چیزی رو حدس زد باید اول لاگ و شواهد رو دید
اینکه بعضی از افراد نمیتونن وصل بشن بیان دقیقی نیست
شاید کانفیگ رو عوض کردید و کانفیگ اپدیت شده رو بهشون ندادید.
براشون مجدد بفرستید
همین که سرور کار میکنه یعنی سمت سرور کاری برای انجام نیست

**Comment by saliarman77** [comment]
سلام گل
اول میخواستم بابت پروژه خوبت ازت تشکر کنم 
دوم اینکه ی سوال داشتم ازت میخواستم ببینم اطلاعات مربوط به یوزرها داخل کدوم دایرکتوری ذخیره میشن؟

**Comment by aleskxyz** [comment]
/opt/reality-ezpz
