### ISSUE TITLE
Unblock ads

### ISSUE THREAD

**Issue by USTOIR** [aleskxyz/reality-ezpz#95]
Hello. I need a configuration where Google ads are not blocked. How can I edit it?

**Comment by aleskxyz** [comment]
Fork this repo for yourself and remove related lines from script.

**Comment by USTOIR** [comment]
Can you advise which lines should be removed in the forked version?

**Comment by aleskxyz** [comment]
for the repo, inform me to change the code on your fork

**Comment by USTOIR** [comment]
https://github.com/USTOIR/reality-ezpz-adsallowed

**Comment by aleskxyz** [comment]
https://github.com/USTOIR/reality-ezpz-adsallowed/pull/1
