### ISSUE TITLE
نصب

### ISSUE THREAD

**Issue by nimaafallah** [aleskxyz/reality-ezpz#97]
سلام 
موقع نصب این پیام رو میده ، ممنون میشم راهنماییم کنید.

curl: (22) The requested URL returned error: 403 Forbidden
Failed to enable unit: Unit file docker.service does not exist.

**Comment by sakhrearasp** [comment]
سلام! خطاهایی که در این پیام مشاهده می‌کنید، مربوط به دو مسئله جداگانه است:
1. خطا 403 Forbidden:
این خطا نشان می‌دهد که سرور مورد نظر درخواست شما را رد کرده و دسترسی لازم را نمی‌دهد. احتمالاً دلیل این خطا می‌تواند این باشد که شما دسترسی مجاز به منبع درخواستی را نداشته باشید. این می‌تواند به دلیل اشتباه در آدرس منبع، محدودیت‌های دسترسی کاربر، یا تنظیمات سرور باشد. بررسی کنید که آدرس صحیح است و شما به درستی دسترسی دارید. در صورتی که مشکل ادامه دارد، باید با مدیر سیستم یا صاحب سرور تماس بگیرید تا مشکل را بررسی کنند.

2. خطا Failed to enable unit: Unit file docker.service does not exist:
این خطا نشان می‌دهد که سرویس Docker در سیستم شما وجود ندارد. Docker یک پلتفرم محبوب برای مدیریت و اجرای برنامه‌ها در بستر محیط‌های مجازی است. برای رفع این خطا، نیاز است که Docker را در سیستم خود نصب و پیکربندی کنید. شما باید مطمئن شوید که Docker به درستی نصب شده است و سرویس آن در سیستم فعال شده است. برای این کار، می‌توانید مستندات رسمی Docker را بررسی کنید و دستورها مربوط را برای نصب و فعال‌سازی Docker روی سیستم خودتان اجرا کنید.

**Comment by aleskxyz** [comment]
> سلام موقع نصب این پیام رو میده ، ممنون میشم راهنماییم کنید.
> 
> curl: (22) The requested URL returned error: 403 Forbidden Failed to enable unit: Unit file docker.service does not exist.

سلام
به نظر میاد شبکه شما محدودیتی داره یا آی پی شما بلاک شده. چون خطای ۴۰۳ چیزی جز این نمیتونه باشه
آی پی سرور رو عوض کنید احتمالا حل بشه
