### ISSUE TITLE
ShadowRocket

### ISSUE THREAD

**Issue by Kasraz1368** [aleskxyz/reality-ezpz#98]
سلام و وقت بخیر
hysteria 2 , Tuic
با اینکه Shadowrocket پروتکل هاشو اضافه کرده اما کار نمیکنه
تنظیمات خاصی داره؟

**Comment by aleskxyz** [comment]
سلام
لطفا توی اون اپلیکیشن برای این پروتکلها یه کانفیگ بسازید و فیلدها رو با اطلاعات ساختگی پر کنید و از اون کانفیگ خروجی بگیرید و بفرستید تا بررسی کنم

**Comment by Kasraz1368** [comment]
سلام ممنونم از پاسختون 
در واقع من هم اطلاعات رو به صورت دستی وارد کردم هم به صورت اسکن کردن بارکد اما هر دوش جواب نداد
اما همین کانفیگ روی Nekobox به راحتی کانکت میشه
tuic://8cd1c835-3977-459b-959b-96280e9bdgj8:9ef10cc3b31fduyfucyf@6.76.88.129:443?congestion_control=bbr&udp_relay_mode=quic&allow_insecure=1#tuic

**Comment by aleskxyz** [comment]
راستش من خودم ایفون ندارم بتونم تست کنم ولی اگه توی بقیه اپ ها کار میکنه و توی شدوراکت کار نمیکنه احتمالا یه چیزی توی خود اپ مشکل داره
